# Numpy

## Importing Numpy library

In [168]:
import numpy as np

## Basic Array creation

In [169]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [170]:
np.array(a)

array([1, 2, 3, 4])

In [171]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [172]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array generation function

In [173]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [175]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [176]:
arr= np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [177]:
arr= np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [178]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [179]:
arr=np.linspace(1,5,3) #linear space
arr

array([1., 3., 5.])

## Random Generation function

In [180]:
np.random.rand(10) #between 0-1 ...concept of normalization

array([0.09556626, 0.44084335, 0.20715824, 0.05029251, 0.06506281,
       0.11857468, 0.80784019, 0.02669905, 0.39542616, 0.4644683 ])

In [181]:
np.random.randn(10) #between -3 - 3 ...concept of standardization

array([ 1.0034527 ,  0.26362668, -1.29494411,  0.51580155,  0.3840821 ,
        0.05769443,  1.21946281,  0.90941178, -0.46868216,  0.1646581 ])

In [182]:
np.random.randint(6) #between 0-6

3

In [183]:
np.random.randint(10,20,5) # low, high, numbers to be generated

array([15, 17, 11, 11, 11])

## Array Attributes

In [184]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
arr.shape

(3, 3)

In [186]:
arr.size

9

In [187]:
arr.dtype

dtype('int32')

## Array methods

In [188]:
arr.min()

1

In [189]:
arr.max()

9

In [190]:
arr.sum()

45

In [191]:
np.sum(arr,axis=0) # 0 is vertical axis column wise

array([12, 15, 18])

In [192]:
np.sum(arr,axis=1) # 1 is horizontal axis row wise

array([ 6, 15, 24])

In [193]:
arr.mean()

5.0

In [194]:
arr.std()

2.581988897471611

In [195]:
arr.argmax() #index of max element

8

In [196]:
arr.argmin() #index of min element

0

## Reshaping and Resizing

In [197]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [198]:
# from 1D to 2D
arr=arr.reshape(6,5)

In [199]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Array Indexing

## Numpy indexing and slicing of vectors

In [200]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [201]:
arr[6]

17

In [202]:
arr[3::2]

array([14, 16, 18, 20])

## Numpy indexing and slicing of matrix

In [203]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [204]:
arr[0]

array([1, 2, 3, 4, 5])

In [205]:
arr[0,0]

1

In [206]:
arr[5,4]

30

In [207]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

## boolean indexing

In [208]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [209]:
bool_index=arr%2==0

In [210]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [211]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array operations

## Arithematic operations

In [212]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [213]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [214]:
a1-a2

array([-5, -5, -5, -5, -5])

In [215]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [216]:
a1 /a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [217]:
a1 // a2

array([0, 0, 0, 0, 0])

In [218]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

## Broadcasting

In [219]:
l=[10,20,30,40]
arr=np.array(l)

In [220]:
arr+10 # broadcasting is like adding single element to all the elements

#Broadcasting is the method used by NumPy to apply operations element-wise on arrays of
#different shapes by automatically expanding their shapes to make them compatible.

array([20, 30, 40, 50])

## Deep and Shallow copy

In [221]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [222]:
slice=a[:5]
slice=slice*10
slice

#shallow copy

array([10, 20, 30, 40, 50])

In [223]:
a[4:6]*10

array([50, 60])

In [224]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [225]:
b=a #deep copy

In [226]:
b[0]=99

In [227]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [228]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [229]:
c=a.copy() #shallow copy

In [230]:
c[0]=10
c

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [231]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Matrix operations

In [232]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])

In [233]:
A

array([[1, 2],
       [3, 4]])

In [234]:
B

array([[5, 6],
       [7, 8]])

In [235]:
A@B

array([[19, 22],
       [43, 50]])

In [236]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [237]:
A.T

array([[1, 3],
       [2, 4]])

In [238]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

## Advance Array Manipulation

### Stacking Array

In [239]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [240]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [241]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [242]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### splitting Array

In [243]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [244]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [245]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Numpy Exercies

#### Valid Sudoku Checker

In [246]:
import numpy as np

In [247]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [248]:
# sum of each row or column should be 45 respectively

In [249]:
b= np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("Sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [250]:
c=  np.sum(s,axis=0)
for i in b:
    if i!=45:
        print("Sudoku is not valid")
        break
else:
    print("for columns it is valid")

for columns it is valid


In [251]:
valid= True
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        if n.sum()!=45:
            valid=False

if valid:
    print("This is a Valid Sudoku")
else:
    print("invalid Sudoku")
        

This is a Valid Sudoku


## Student data

In [252]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [253]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [254]:
#Find the average age of students
np.mean(data[:,0])

18.4

In [255]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [256]:
#Find the highest Science mark.
np.max(data[:,2])

95

In [257]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [258]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [259]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [260]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [261]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [262]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])